name: fiap_tsp
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - git=2.45.2=haa95532_1
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py39haa95532_0
  - python=3.9.19=h1aa4202_1
  - setuptools=75.1.0=py39haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - wheel=0.44.0=py39haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - altair==5.4.1
      - attrs==24.2.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.54.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.10
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - narwhals==1.8.3
      - numpy==2.0.2
      - packaging==24.1
      - pandas==2.2.3
      - pillow==10.4.0
      - protobuf==5.28.2
      - pyarrow==17.0.0
      - pydeck==0.9.1
      - pygame==2.6.0
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - referencing==0.35.1
      - requests==2.32.3
      - rich==13.8.1
      - rpds-py==0.20.0
      - six==1.16.0
      - smmap==5.0.1
      - streamlit==1.38.0
      - tenacity==8.5.0
      - toml==0.10.2
      - tornado==6.4.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - watchdog==4.0.2
      - zipp==3.20.2

      